apiVersion: v1
kind: Service
metadata:
  name: consumer-svc
spec:
  ports:
    - name: http
      # The port that will be exposed by the Service
      port: 8080
      # The port on the Pod that the traffic will be forwarded to
      targetPort: 8080
  selector:
    app: consumer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deployment
  labels:
    app: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      initContainers:
        - name: wait-for-kafka
          image: busybox:1.28
          command: ['sh', '-c', 'until nc -z -v -w30 kafka.app.svc.cluster.local 9092; do echo "Waiting for Kafka..."; sleep 5; done;']
      containers:
        - name: consumer-pod
          image: consumer:latest
          imagePullPolicy: Never
          ports:
          - containerPort: 8080
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
          env:
          - name: KAFKA_BROKERS
            # <service-name>.<namespace>.svc.cluster.local:<port>
            value: "kafka.app.svc.cluster.local:9092"
          - name: KAFKA_TOPIC
            value: "container.telemetry"
          - name: LISTEN_ADDR
            value: ":8080"
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: telemetry-timescaledb-app
                key: uri
