# infra/gateway/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # 按依賴順序排列
  - gateway-class.yaml
  - gateway.yaml
  - security-policy.yaml
  - keycloak-route.yaml
  # - apps/example/
  # - apps/foo/
  # - apps/bar/
  # - apps/allen/
