apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: global-rate-limit
  labels:
    global: "true"
  annotations:
    kubernetes.io/ingress.class: kong
config:
  minute: 5
  policy: redis
  redis_host: redis.redis.svc.cluster.local
  redis_port: 6379
  redis_timeout: 2000
plugin: rate-limiting
