apiVersion: v1
kind: Service
metadata:
  name: ruleengine-svc
spec:
  ports:
    - name: http
      port: 8082
      targetPort: 8082
  selector:
    app: ruleengine
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruleengine-deployment
  labels:
    app: ruleengine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ruleengine
  template:
    metadata:
      labels:
        app: ruleengine
    spec:
      initContainers:
        - name: wait-for-kafka
          image: busybox:1.28
          command: ['sh', '-c', 'until nc -z -v -w30 kafka.app.svc.cluster.local 9092; do echo "Waiting for Kafka..."; sleep 5; done;']
      containers:
        - name: ruleengine-pod
          image: ruleengine:latest
          imagePullPolicy: Never
          ports:
          - containerPort: 8082
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
          env:
          - name: KAFKA_BROKERS
            value: "kafka.app.svc.cluster.local:9092"
          - name: KAFKA_TOPIC
            value: "container.telemetry"
          - name: KAFKA_GROUP
            value: "ruleengine-service"
          - name: NOTIFY_TOPIC
            value: "geofence.events"
          - name: LISTEN_ADDR
            value: ":8082"
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: ruleengine-db-app
                key: uri
